const p = (file: string) => `/products/${file}`;

export const productImages: Record<string, string> = {
  // ── VEGETABLES ──────────────────────────────────────────────────
  f1:  p("asparagus.webp"),
  f2:  p("beans.webp"),
  f3:  p("prod_beetroot.webp"),
  f4:  p("broccoli.webp"),
  f5:  p("broccolini.webp"),
  f6:  p("prod_cabbage.webp"),
  f7:  p("purple_red.webp"),
  f8:  p("prod_capsicum.webp"),
  f9:  p("prod_capsicum.webp"),
  f10: p("prod_carrots.webp"),
  f11: p("cauliflower.webp"),
  f12: p("prod_celery.webp"),
  f13: p("chili.webp"),
  f14: p("chili.webp"),
  f15: p("cucumber.webp"),
  f16: p("cucumber.webp"),
  f17: p("daikon.webp"),
  f18: p("eggplant.webp"),
  f19: p("prod_shallots.webp"),
  f20: p("garlic.webp"),
  f21: p("peeled_ginger.webp"),
  f22: p("chili.webp"),
  f23: p("prod_leek.webp"),
  f24: p("salad_greens.webp"),
  f25: p("purple_green.webp"),
  f26: p("salad_greens.webp"),
  f27: p("salad_greens.webp"),
  f28: p("purple_green.webp"),
  f29: p("prod_mushrooms.webp"),
  f30: p("prod_mushrooms.webp"),
  f31: p("prod_onions.webp"),
  f32: p("prod_onions.webp"),
  f33: p("prod_onions.webp"),
  f34: p("parsnip.webp"),
  f35: p("prod_potatoes.webp"),
  f36: p("prod_potatoes.webp"),
  f37: p("prod_potatoes.webp"),
  f38: p("prod_potatoes.webp"),
  f39: p("prod_potatoes.webp"),
  f40: p("prod_potatoes.webp"),
  f41: p("prod_potatoes.webp"),
  f42: p("prod_pumpkin.webp"),
  f43: p("prod_pumpkin.webp"),
  f44: p("prod_pumpkin.webp"),
  f45: p("silverbeet.webp"),
  f46: p("snow_peas.webp"),
  f47: p("squash.webp"),
  f48: p("swede.webp"),
  f49: p("sweet_corn.webp"),
  f50: p("tomatoes.webp"),
  f51: p("tomatoes_cherry.webp"),
  f52: p("tomatoes_roma.webp"),
  f53: p("turnip.webp"),
  f54: p("prod_zucchini.webp"),

  // ── FRUIT ────────────────────────────────────────────────────────
  f55: p("apples.webp"),
  f56: p("apples.webp"),
  f57: p("apples.webp"),
  f58: p("apples.webp"),
  f60: p("avocado.webp"),
  f61: p("bananas.webp"),
  f62: p("berries.webp"),
  f64: p("citrus_fruits.webp"),
  f65: p("grapes.webp"),
  f66: p("grapes.webp"),
  f67: p("kiwi_fruit.webp"),
  f68: p("citrus_fruits.webp"),
  f69: p("citrus_fruits.webp"),
  f70: p("citrus_fruits.webp"),
  f71: p("mango.webp"),
  f72: p("melon.webp"),
  f73: p("melon.webp"),
  f74: p("melon.webp"),
  f76: p("citrus_fruits.webp"),
  f77: p("citrus_fruits.webp"),
  f78: p("citrus_fruits.webp"),
  f79: p("passion_fruit.webp"),
  f83: p("pears.webp"),
  f84: p("pineapples.webp"),
  f86: p("berries.webp"),
  f87: p("prod_strawberries.webp"),

  // ── HERBS ────────────────────────────────────────────────────────
  f88: p("herbs_assorted.webp"),
  f89: p("herbs_assorted.webp"),
  f90: p("herbs_assorted.webp"),
  f91: p("herbs_assorted.webp"),
  f92: p("herbs_assorted.webp"),
  f93: p("herbs_assorted.webp"),
  f94: p("herbs_assorted.webp"),
  f95: p("herbs_assorted.webp"),
  f96: p("herbs_assorted.webp"),
  f97: p("herbs_assorted.webp"),
  f98: p("herbs_assorted.webp"),
  f99: p("herbs_assorted.webp"),

  // ── CHINESE VEG ──────────────────────────────────────────────────
  f100: p("chinese_vegetables.webp"),
  f101: p("chinese_vegetables.webp"),
  f102: p("chinese_vegetables.webp"),
  f103: p("chinese_vegetables.webp"),

  // ── OTHER (fresh) ────────────────────────────────────────────────
  f104: p("alfalfa.webp"),
  f105: p("salad_greens.webp"),
  f106: p("bean_sprouts.webp"),
  f107: p("eggs.webp"),
  f108: p("kale.webp"),
  f109: p("salad_greens.webp"),
  f110: p("snow_pea_sprouts.webp"),
  f111: p("prod_wombok.webp"),

  // ── POTATO PRODUCTS ──────────────────────────────────────────────
  pr1:  p("prod_potatoes.webp"),
  pr2:  p("prod_potatoes.webp"),
  pr3:  p("prod_potatoes.webp"),
  pr4:  p("prod_potatoes.webp"),
  pr5:  p("prod_potatoes.webp"),
  pr6:  p("prod_potatoes.webp"),
  pr7:  p("prod_potatoes.webp"),
  pr8:  p("prod_potatoes.webp"),
  pr9:  p("prod_potatoes.webp"),
  pr10: p("prod_potatoes.webp"),
  pr11: p("prod_potatoes.webp"),
  pr12: p("prod_potatoes.webp"),

  // ── SWEET POTATO PRODUCTS ────────────────────────────────────────
  pr13: p("prod_sweet_potatoes.webp"),
  pr14: p("prod_sweet_potatoes.webp"),
  pr15: p("prod_sweet_potatoes.webp"),
  pr16: p("prod_sweet_potatoes.webp"),
  pr17: p("prod_sweet_potatoes.webp"),
  pr18: p("prod_sweet_potatoes.webp"),

  // ── PUMPKIN PRODUCTS ─────────────────────────────────────────────
  pr19: p("prod_pumpkin.webp"),
  pr20: p("prod_pumpkin.webp"),
  pr21: p("prod_pumpkin.webp"),
  pr22: p("prod_pumpkin.webp"),
  pr23: p("prod_pumpkin.webp"),
  pr24: p("prod_pumpkin.webp"),
  pr25: p("prod_pumpkin.webp"),
  pr26: p("prod_pumpkin.webp"),
  pr27: p("prod_pumpkin.webp"),

  // ── ONION PRODUCTS ───────────────────────────────────────────────
  pr28: p("prod_onions.webp"),
  pr29: p("prod_onions.webp"),
  pr30: p("prod_onions.webp"),
  pr31: p("prod_onions.webp"),
  pr32: p("prod_onions.webp"),
  pr33: p("prod_onions.webp"),
  pr34: p("prod_onions.webp"),
  pr35: p("prod_onions.webp"),
  pr36: p("prod_onions.webp"),
  pr37: p("prod_onions.webp"),

  // ── CARROT PRODUCTS ──────────────────────────────────────────────
  pr38: p("prod_carrots.webp"),
  pr39: p("prod_carrots.webp"),
  pr40: p("prod_carrots.webp"),
  pr41: p("prod_carrots.webp"),
  pr42: p("prod_carrots.webp"),
  pr43: p("prod_carrots.webp"),
  pr44: p("prod_carrots.webp"),
  pr45: p("prod_carrots.webp"),
  pr46: p("prod_carrots.webp"),
  pr47: p("prod_carrots.webp"),
  pr48: p("prod_carrots.webp"),

  // ── OTHERS (processed) ───────────────────────────────────────────
  pr49: p("beans.webp"),
  pr50: p("prod_beetroot.webp"),
  pr51: p("prod_beetroot.webp"),
  pr52: p("prod_cabbage.webp"),
  pr53: p("prod_capsicum.webp"),
  pr54: p("prod_capsicum.webp"),
  pr55: p("prod_celery.webp"),
  pr56: p("cucumber.webp"),
  pr57: p("salad_greens.webp"),
  pr58: p("prod_cabbage.webp"),
  pr59: p("broccoli.webp"),
  pr60: p("cauliflower.webp"),
  pr61: p("fruit_salad_platter.webp"),
  pr62: p("shredded_lettuce.webp"),
  pr63: p("prod_mushrooms.webp"),
  pr64: p("citrus_fruits.webp"),
  pr65: p("parsnip.webp"),
  pr66: p("pineapples.webp"),
  pr67: p("prod_cabbage.webp"),
  pr68: p("roast_mix.webp"),
  pr69: p("soup_mix.webp"),
  pr70: p("soup_mix.webp"),
  pr71: p("stir_fry_mix.webp"),
  pr72: p("stir_fry_mix.webp"),
  pr73: p("stir_fry_mix.webp"),
  pr74: p("prod_swede.webp"),
  pr75: p("prod_swede.webp"),
  pr76: p("tomatoes.webp"),
  pr77: p("tomatoes.webp"),
  pr78: p("tossed_salad.webp"),
  pr79: p("turnip.webp"),
  pr80: p("melon.webp"),
  pr81: p("prod_zucchini.webp"),
  pr82: p("prod_zucchini.webp"),
  pr83: p("prod_zucchini.webp"),
  pr84: p("prod_zucchini.webp"),
  pr85: p("fruit_salad_platter.webp"),
};
